spring:
  application:
    name: cloud-auth
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  #redis 配置
  redis:
    database: 0
    host: 192.168.0.250
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: ylz1234
    port: 6379
  datasource:
    name: cloud
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  rabbitmq:
    host: 192.168.0.250
    port: 5672
    virtual-host: /spring-cloud
    username: admin
    password: 123456
  zipkin:
    enabled: true
  sleuth:
    sampler:
      percentage: 1
mybatis:
  basepackage: com.lvhaifeng.cloud.auth.server.modules
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"

server:
  port: 9777 #启动端口

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

jwt:
  key: RSA
  token-header: Authorization
  expire: 3600
  rsa-secret: xx1WET12^%3^(WE45
  user-service: cloud-admin

client:
  id: cloud-auth
  secret: 123456
  token-header: client-token
  expire: 3600
  rsa-secret: x2318^^(*WRYQWR(QW&T

#redis-cache 相关
redis:
  aec-key: xx288&^^%$!@#4dc
  aec-iv: 0123456789abcdef

mapper:
  mappers: com.lvhaifeng.cloud.common.mapper.CommonMapper


logging:
  level:
    root: info
    org.springframework.integration.endpoint.SourcePollingChannelAdapter: info
