spring:
    application:
        name: cloud-center

server:
    port: 8761
    responseCacheUpdateIntervalMs: 3000
    responseCacheAutoExpirationInSeconds: 180
    eviction-interval-timer-in-ms: 3000
    enable-self-preservation: false

eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: false
    fetch-registry: false
