server:
  port: 8750 #启动端口

spring:
  profiles:
    active: native
  application:
    name: cloud-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/

  rabbitmq:
    host: 192.168.0.250
    port: 5672
    username: admin
    password: 123456
    connection-timeout: 15
    virtual-host: /spring-cloud
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        retry:
          enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  user:
    name: lvhaifeng
    password: 135976

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
