server:
  port: 8750 #启动端口

spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://git@github.com:lhf-programer/spring-cloud.git
          searchPaths: cloud-config
  rabbitmq:
    host: 192.168.42.128
    port: 5672
    username: admin
    password: admin
    connection-timeout: 15
    virtual-host: /spring-cloud
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        retry:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
